import { createContext, useContext, useState, ReactNode, useEffect } from "react";

export type Language = "sr" | "hr" | "bs" | "me" | "mk" | "sl" | "en" | "ru" | "uk";

export interface LanguageInfo {
  code: Language;
  name: string;
  nativeName: string;
  flag: string;
}

export const languages: LanguageInfo[] = [
  { code: "sr", name: "Serbian", nativeName: "Srpski", flag: "🇷🇸" },
  { code: "hr", name: "Croatian", nativeName: "Hrvatski", flag: "🇭🇷" },
  { code: "bs", name: "Bosnian", nativeName: "Bosanski", flag: "🇧🇦" },
  { code: "me", name: "Montenegrin", nativeName: "Crnogorski", flag: "🇲🇪" },
  { code: "mk", name: "Macedonian", nativeName: "Македонски", flag: "🇲🇰" },
  { code: "sl", name: "Slovenian", nativeName: "Slovenščina", flag: "🇸🇮" },
  { code: "en", name: "English", nativeName: "English", flag: "🇬🇧" },
  { code: "ru", name: "Russian", nativeName: "Русский", flag: "🇷🇺" },
  { code: "uk", name: "Ukrainian", nativeName: "Українська", flag: "🇺🇦" },
];

// UI translations for each language
export const translations: Record<Language, Record<string, string>> = {
  sr: {
    appName: "Poruke.AI",
    tagline: "Piši bolje, brže, lakše",
    signIn: "Prijavi se",
    signOut: "Odjavi se",
    signUp: "Registruj se",
    email: "Email",
    password: "Lozinka",
    back: "Nazad",
    next: "Dalje",
    generateMessage: "Generiši poruku",
    signInToGenerate: "Prijavi se da generišeš",
    newMessage: "Nova poruka",
    yourMessage: "Tvoja poruka",
    copyToClipboard: "Kopiraj",
    copied: "Kopirano!",
    regenerate: "Generiši ponovo",
    generating: "Generiše se poruka...",
    loading: "Učitavanje...",
    stepSituation: "Situacija",
    stepGoal: "Cilj",
    stepTone: "Ton",
    stepContext: "Kontekst",
    whatIsItAbout: "O čemu se radi?",
    whatDoYouWantToAchieve: "Šta želiš da postigneš?",
    howShouldItSound: "Kako da zvuči?",
    describeSituation: "Opiši situaciju",
    describeContext: "Kratko objasni kontekst u 1-2 rečenice.",
    contextPlaceholder: "Npr: Kolega mi nije vratio novac već mesec dana, a ne znam kako da ga podsetim a da ne bude neprijatno...",
    situationWork: "Posao",
    situationWorkDesc: "Kolege, šefovi, klijenti",
    situationHousing: "Stanovanje",
    situationHousingDesc: "Stanodavci, komšije",
    situationPrivate: "Privatno",
    situationPrivateDesc: "Porodica, prijatelji",
    situationBuying: "Kupoprodaja",
    situationBuyingDesc: "Oglasi, dogovori",
    situationLove: "Muvanje 💕",
    situationLoveDesc: "IG, Messenger, uživo",
    situationBadNews: "Loše vesti",
    situationBadNewsDesc: "Teške teme, ozbiljno",
    goalRemind: "Podsetiti",
    goalRemindDesc: "Nekoga na nešto",
    goalRefuse: "Odbiti",
    goalRefuseDesc: "Zahtev ili ponudu",
    goalAsk: "Zamoliti",
    goalAskDesc: "Za uslugu ili pomoć",
    goalCalm: "Smiriti",
    goalCalmDesc: "Napetu situaciju",
    goalClarify: "Razjasniti",
    goalClarifyDesc: "Nesporazum",
    goalOpener: "Započeti razgovor",
    goalOpenerDesc: "Ice-breaker, prva poruka",
    goalFlirt: "Flertovati",
    goalFlirtDesc: "Pokazati interesovanje",
    goalCompliment: "Kompliment",
    goalComplimentDesc: "Originalan, kreativan",
    goalAskOut: "Pozvati na piće",
    goalAskOutDesc: "Kafu, izlazak, dejt",
    goalBreakup: "Raskid",
    goalBreakupDesc: "Prekinuti vezu",
    goalReject: "Odbiti nekoga",
    goalRejectDesc: "Bez povređivanja",
    goalInform: "Saopštiti vest",
    goalInformDesc: "Lošu informaciju",
    goalApologize: "Izviniti se",
    goalApologizeDesc: "Iskreno, od srca",
    goalNegotiate: "Pregovarati",
    goalNegotiateDesc: "Cenu, uslove, rokove",
    goalPropose: "Predložiti",
    goalProposeDesc: "Ideju, projekat, saradnju",
    goalFollowup: "Follow-up",
    goalFollowupDesc: "Nastavak razgovora",
    goalAnnounce: "Najaviti",
    goalAnnounceDesc: "Vest, događaj, promenu",
    goalThank: "Zahvaliti se",
    goalThankDesc: "Na pomoći, saradnji",
    goalFeedback: "Dati feedback",
    goalFeedbackDesc: "Pozitivno ili konstruktivno",
    goalCustom: "Drugo...",
    goalCustomDesc: "Napiši svoj cilj",
    customGoalPlaceholder: "Opiši šta želiš da postigneš...",
    customGoalHint: "Npr: Želim da pozovem kolegu na ručak bez da zvuči kao dejt",
    tonePolite: "Ljubazno",
    tonePoliteDesc: "Prijateljski, toplo",
    toneProfessional: "Profesionalno",
    toneProfessionalDesc: "Jasno, samouvereno",
    toneDirect: "Direktno",
    toneDirectDesc: "Iskreno, bez okolišanja",
    toneCalm: "Smireno",
    toneCalmDesc: "Kontrolisano, sa razumevanjem",
    tonePlayful: "Zaigrano",
    tonePlayfulDesc: "Šarmantno, duhovito",
    toneFlirty: "Flertovački",
    toneFlirtyDesc: "Sa podtekstom",
    toneGentle: "Nežno",
    toneGentleDesc: "Obzirno, empatično",
    createAccount: "Kreiraj nalog",
    enterCredentials: "Unesite vaše podatke za prijavu",
    freeMessages: "Besplatno dobijate 5 poruka",
    wrongCredentials: "Pogrešan email ili lozinka",
    userExists: "Korisnik sa ovim emailom već postoji",
    confirmEmail: "Potvrdite email adresu",
    accountCreated: "Nalog je kreiran. Možete se prijaviti.",
    noAccount: "Nemate nalog? Registrujte se",
    hasAccount: "Već imate nalog? Prijavite se",
    pleaseWait: "Molimo sačekajte...",
    premium: "Premium",
    messagesLeft: "poruka",
    usedMessages: "Iskorišćeno",
    unlimited: "Neograničene poruke",
    freeLimit: "Besplatno: 5 poruka",
    signInToStart: "Prijavite se da počnete",
    subscribeForUnlimited: "Pretplata za neograničeno",
    limitReached: "Iskoristili ste svih 5 besplatnih poruka.",
    subscribe: "Pretplatite se za neograničeno",
    messageHistory: "Istorija poruka",
    noHistory: "Još nemate generisanih poruka",
    error: "Greška",
    mustBeSignedIn: "Morate biti prijavljeni da biste generisali poruke",
    invalidSession: "Nevalidna sesija. Prijavite se ponovo.",
    errorCheckingLimit: "Greška pri proveri limita",
    errorGenerating: "Nije moguće generisati poruku. Pokušajte ponovo.",
    tooManyRequests: "Previše zahteva. Sačekajte malo i pokušajte ponovo.",
    serviceUnavailable: "Servis trenutno nije dostupan.",
    noResponse: "Nema odgovora od AI servisa",
  },
  hr: {
    appName: "Poruke.AI",
    tagline: "Piši bolje, brže, lakše",
    signIn: "Prijavi se",
    signOut: "Odjavi se",
    signUp: "Registriraj se",
    email: "Email",
    password: "Lozinka",
    back: "Natrag",
    next: "Dalje",
    generateMessage: "Generiraj poruku",
    signInToGenerate: "Prijavi se za generiranje",
    newMessage: "Nova poruka",
    yourMessage: "Tvoja poruka",
    copyToClipboard: "Kopiraj",
    copied: "Kopirano!",
    regenerate: "Generiraj ponovo",
    generating: "Generira se poruka...",
    loading: "Učitavanje...",
    stepSituation: "Situacija",
    stepGoal: "Cilj",
    stepTone: "Ton",
    stepContext: "Kontekst",
    whatIsItAbout: "O čemu se radi?",
    whatDoYouWantToAchieve: "Što želiš postići?",
    howShouldItSound: "Kako treba zvučati?",
    describeSituation: "Opiši situaciju",
    describeContext: "Ukratko objasni kontekst u 1-2 rečenice.",
    contextPlaceholder: "Npr: Kolega mi nije vratio novac već mjesec dana, a ne znam kako ga podsjetiti, a da ne bude neugodno...",
    situationWork: "Posao",
    situationWorkDesc: "Kolege, šefovi, klijenti",
    situationHousing: "Stanovanje",
    situationHousingDesc: "Stanodavci, susjedi",
    situationPrivate: "Privatno",
    situationPrivateDesc: "Obitelj, prijatelji",
    situationBuying: "Kupoprodaja",
    situationBuyingDesc: "Oglasi, dogovori",
    situationLove: "Muvanje 💕",
    situationLoveDesc: "IG, Messenger, uživo",
    situationBadNews: "Loše vijesti",
    situationBadNewsDesc: "Teške teme, ozbiljno",
    goalRemind: "Podsjetiti",
    goalRemindDesc: "Nekoga na nešto",
    goalRefuse: "Odbiti",
    goalRefuseDesc: "Zahtjev ili ponudu",
    goalAsk: "Zamoliti",
    goalAskDesc: "Za uslugu ili pomoć",
    goalCalm: "Smiriti",
    goalCalmDesc: "Napetu situaciju",
    goalClarify: "Razjasniti",
    goalClarifyDesc: "Nesporazum",
    goalOpener: "Započeti razgovor",
    goalOpenerDesc: "Ice-breaker, prva poruka",
    goalFlirt: "Flertati",
    goalFlirtDesc: "Pokazati interes",
    goalCompliment: "Kompliment",
    goalComplimentDesc: "Originalan, kreativan",
    goalAskOut: "Pozvati na piće",
    goalAskOutDesc: "Kavu, izlazak, dejt",
    goalBreakup: "Prekid",
    goalBreakupDesc: "Prekinuti vezu",
    goalReject: "Odbiti nekoga",
    goalRejectDesc: "Bez povrijeđivanja",
    goalInform: "Priopćiti vijest",
    goalInformDesc: "Lošu informaciju",
    goalApologize: "Ispričati se",
    goalApologizeDesc: "Iskreno, od srca",
    goalNegotiate: "Pregovarati",
    goalNegotiateDesc: "Cijenu, uvjete, rokove",
    goalPropose: "Predložiti",
    goalProposeDesc: "Ideju, projekt, suradnju",
    goalFollowup: "Follow-up",
    goalFollowupDesc: "Nastavak razgovora",
    goalAnnounce: "Najaviti",
    goalAnnounceDesc: "Vijest, događaj, promjenu",
    goalThank: "Zahvaliti se",
    goalThankDesc: "Na pomoći, suradnji",
    goalFeedback: "Dati feedback",
    goalFeedbackDesc: "Pozitivno ili konstruktivno",
    goalCustom: "Drugo...",
    goalCustomDesc: "Napiši svoj cilj",
    customGoalPlaceholder: "Opiši što želiš postići...",
    customGoalHint: "Npr: Želim pozvati kolegu na ručak bez da zvuči kao dejt",
    tonePolite: "Ljubazno",
    tonePoliteDesc: "Prijateljski, toplo",
    toneProfessional: "Profesionalno",
    toneProfessionalDesc: "Jasno, samouvjereno",
    toneDirect: "Direktno",
    toneDirectDesc: "Iskreno, bez okolišanja",
    toneCalm: "Smireno",
    toneCalmDesc: "Kontrolirano, s razumijevanjem",
    tonePlayful: "Zaigrano",
    tonePlayfulDesc: "Šarmantno, duhovito",
    toneFlirty: "Flertovački",
    toneFlirtyDesc: "S podtekstom",
    toneGentle: "Nježno",
    toneGentleDesc: "Obzirno, empatično",
    createAccount: "Kreiraj račun",
    enterCredentials: "Unesite vaše podatke za prijavu",
    freeMessages: "Besplatno dobivate 5 poruka",
    wrongCredentials: "Pogrešan email ili lozinka",
    userExists: "Korisnik s ovim emailom već postoji",
    confirmEmail: "Potvrdite email adresu",
    accountCreated: "Račun je kreiran. Možete se prijaviti.",
    noAccount: "Nemate račun? Registrirajte se",
    hasAccount: "Već imate račun? Prijavite se",
    pleaseWait: "Molimo pričekajte...",
    premium: "Premium",
    messagesLeft: "poruka",
    usedMessages: "Iskorišteno",
    unlimited: "Neograničene poruke",
    freeLimit: "Besplatno: 5 poruka",
    signInToStart: "Prijavite se za početak",
    subscribeForUnlimited: "Pretplata za neograničeno",
    limitReached: "Iskoristili ste svih 5 besplatnih poruka.",
    subscribe: "Pretplatite se za neograničeno",
    messageHistory: "Povijest poruka",
    noHistory: "Još nemate generiranih poruka",
    error: "Greška",
    mustBeSignedIn: "Morate biti prijavljeni za generiranje poruka",
    invalidSession: "Nevalidna sesija. Prijavite se ponovo.",
    errorCheckingLimit: "Greška pri provjeri limita",
    errorGenerating: "Nije moguće generirati poruku. Pokušajte ponovo.",
    tooManyRequests: "Previše zahtjeva. Pričekajte malo i pokušajte ponovo.",
    serviceUnavailable: "Servis trenutno nije dostupan.",
    noResponse: "Nema odgovora od AI servisa",
  },
  bs: {
    appName: "Poruke.AI",
    tagline: "Piši bolje, brže, lakše",
    signIn: "Prijavi se",
    signOut: "Odjavi se",
    signUp: "Registruj se",
    email: "Email",
    password: "Lozinka",
    back: "Nazad",
    next: "Dalje",
    generateMessage: "Generiši poruku",
    signInToGenerate: "Prijavi se za generisanje",
    newMessage: "Nova poruka",
    yourMessage: "Tvoja poruka",
    copyToClipboard: "Kopiraj",
    copied: "Kopirano!",
    regenerate: "Generiši ponovo",
    generating: "Generiše se poruka...",
    loading: "Učitavanje...",
    stepSituation: "Situacija",
    stepGoal: "Cilj",
    stepTone: "Ton",
    stepContext: "Kontekst",
    whatIsItAbout: "O čemu se radi?",
    whatDoYouWantToAchieve: "Šta želiš postići?",
    howShouldItSound: "Kako da zvuči?",
    describeSituation: "Opiši situaciju",
    describeContext: "Ukratko objasni kontekst u 1-2 rečenice.",
    contextPlaceholder: "Npr: Kolega mi nije vratio novac već mjesec dana, a ne znam kako da ga podsjetim a da ne bude neprijatno...",
    situationWork: "Posao",
    situationWorkDesc: "Kolege, šefovi, klijenti",
    situationHousing: "Stanovanje",
    situationHousingDesc: "Stanodavci, komšije",
    situationPrivate: "Privatno",
    situationPrivateDesc: "Porodica, prijatelji",
    situationBuying: "Kupoprodaja",
    situationBuyingDesc: "Oglasi, dogovori",
    situationLove: "Muvanje 💕",
    situationLoveDesc: "IG, Messenger, uživo",
    situationBadNews: "Loše vijesti",
    situationBadNewsDesc: "Teške teme, ozbiljno",
    goalRemind: "Podsjetiti",
    goalRemindDesc: "Nekoga na nešto",
    goalRefuse: "Odbiti",
    goalRefuseDesc: "Zahtjev ili ponudu",
    goalAsk: "Zamoliti",
    goalAskDesc: "Za uslugu ili pomoć",
    goalCalm: "Smiriti",
    goalCalmDesc: "Napetu situaciju",
    goalClarify: "Razjasniti",
    goalClarifyDesc: "Nesporazum",
    goalOpener: "Započeti razgovor",
    goalOpenerDesc: "Ice-breaker, prva poruka",
    goalFlirt: "Flertovati",
    goalFlirtDesc: "Pokazati interes",
    goalCompliment: "Kompliment",
    goalComplimentDesc: "Originalan, kreativan",
    goalAskOut: "Pozvati na piće",
    goalAskOutDesc: "Kafu, izlazak, dejt",
    goalBreakup: "Raskid",
    goalBreakupDesc: "Prekinuti vezu",
    goalReject: "Odbiti nekoga",
    goalRejectDesc: "Bez povrijeđivanja",
    goalInform: "Saopštiti vijest",
    goalInformDesc: "Lošu informaciju",
    goalApologize: "Izviniti se",
    goalApologizeDesc: "Iskreno, od srca",
    goalNegotiate: "Pregovarati",
    goalNegotiateDesc: "Cijenu, uslove, rokove",
    goalPropose: "Predložiti",
    goalProposeDesc: "Ideju, projekat, saradnju",
    goalFollowup: "Follow-up",
    goalFollowupDesc: "Nastavak razgovora",
    goalAnnounce: "Najaviti",
    goalAnnounceDesc: "Vijest, događaj, promjenu",
    goalThank: "Zahvaliti se",
    goalThankDesc: "Na pomoći, saradnji",
    goalFeedback: "Dati feedback",
    goalFeedbackDesc: "Pozitivno ili konstruktivno",
    goalCustom: "Drugo...",
    goalCustomDesc: "Napiši svoj cilj",
    customGoalPlaceholder: "Opiši šta želiš postići...",
    customGoalHint: "Npr: Želim pozvati kolegu na ručak bez da zvuči kao dejt",
    tonePolite: "Ljubazno",
    tonePoliteDesc: "Prijateljski, toplo",
    toneProfessional: "Profesionalno",
    toneProfessionalDesc: "Jasno, samopouzdano",
    toneDirect: "Direktno",
    toneDirectDesc: "Iskreno, bez okolišanja",
    toneCalm: "Smireno",
    toneCalmDesc: "Kontrolisano, s razumijevanjem",
    tonePlayful: "Zaigrano",
    tonePlayfulDesc: "Šarmantno, duhovito",
    toneFlirty: "Flertovački",
    toneFlirtyDesc: "S podtekstom",
    toneGentle: "Nježno",
    toneGentleDesc: "Obzirno, empatično",
    createAccount: "Kreiraj račun",
    enterCredentials: "Unesite vaše podatke za prijavu",
    freeMessages: "Besplatno dobijate 5 poruka",
    wrongCredentials: "Pogrešan email ili lozinka",
    userExists: "Korisnik sa ovim emailom već postoji",
    confirmEmail: "Potvrdite email adresu",
    accountCreated: "Račun je kreiran. Možete se prijaviti.",
    noAccount: "Nemate račun? Registrujte se",
    hasAccount: "Već imate račun? Prijavite se",
    pleaseWait: "Molimo sačekajte...",
    premium: "Premium",
    messagesLeft: "poruka",
    usedMessages: "Iskorišteno",
    unlimited: "Neograničene poruke",
    freeLimit: "Besplatno: 5 poruka",
    signInToStart: "Prijavite se da počnete",
    subscribeForUnlimited: "Pretplata za neograničeno",
    limitReached: "Iskoristili ste svih 5 besplatnih poruka.",
    subscribe: "Pretplatite se za neograničeno",
    messageHistory: "Historija poruka",
    noHistory: "Još nemate generisanih poruka",
    error: "Greška",
    mustBeSignedIn: "Morate biti prijavljeni za generisanje poruka",
    invalidSession: "Nevalidna sesija. Prijavite se ponovo.",
    errorCheckingLimit: "Greška pri provjeri limita",
    errorGenerating: "Nije moguće generisati poruku. Pokušajte ponovo.",
    tooManyRequests: "Previše zahtjeva. Sačekajte malo i pokušajte ponovo.",
    serviceUnavailable: "Servis trenutno nije dostupan.",
    noResponse: "Nema odgovora od AI servisa",
  },
  me: {
    appName: "Poruke.AI",
    tagline: "Piši bolje, brže, lakše",
    signIn: "Prijavi se",
    signOut: "Odjavi se",
    signUp: "Registruj se",
    email: "Email",
    password: "Lozinka",
    back: "Nazad",
    next: "Dalje",
    generateMessage: "Generiši poruku",
    signInToGenerate: "Prijavi se za generisanje",
    newMessage: "Nova poruka",
    yourMessage: "Tvoja poruka",
    copyToClipboard: "Kopiraj",
    copied: "Kopirano!",
    regenerate: "Generiši ponovo",
    generating: "Generiše se poruka...",
    loading: "Učitavanje...",
    stepSituation: "Situacija",
    stepGoal: "Cilj",
    stepTone: "Ton",
    stepContext: "Kontekst",
    whatIsItAbout: "O čemu se radi?",
    whatDoYouWantToAchieve: "Šta želiš da postigneš?",
    howShouldItSound: "Kako da zvuči?",
    describeSituation: "Opiši situaciju",
    describeContext: "Ukratko objasni kontekst u 1-2 rečenice.",
    contextPlaceholder: "Npr: Kolega mi nije vratio pare već mjesec dana, a ne znam kako da ga podsjetim a da ne bude neprijatno...",
    situationWork: "Posao",
    situationWorkDesc: "Kolege, šefovi, klijenti",
    situationHousing: "Stanovanje",
    situationHousingDesc: "Stanodavci, komšije",
    situationPrivate: "Privatno",
    situationPrivateDesc: "Porodica, prijatelji",
    situationBuying: "Kupoprodaja",
    situationBuyingDesc: "Oglasi, dogovori",
    situationLove: "Muvanje 💕",
    situationLoveDesc: "IG, Messenger, uživo",
    situationBadNews: "Loše vijesti",
    situationBadNewsDesc: "Teške teme, ozbiljno",
    goalRemind: "Podsjetiti",
    goalRemindDesc: "Nekoga na nešto",
    goalRefuse: "Odbiti",
    goalRefuseDesc: "Zahtjev ili ponudu",
    goalAsk: "Zamoliti",
    goalAskDesc: "Za uslugu ili pomoć",
    goalCalm: "Smiriti",
    goalCalmDesc: "Napetu situaciju",
    goalClarify: "Razjasniti",
    goalClarifyDesc: "Nesporazum",
    goalOpener: "Započeti razgovor",
    goalOpenerDesc: "Ice-breaker, prva poruka",
    goalFlirt: "Flertovati",
    goalFlirtDesc: "Pokazati interes",
    goalCompliment: "Kompliment",
    goalComplimentDesc: "Originalan, kreativan",
    goalAskOut: "Pozvati na piće",
    goalAskOutDesc: "Kafu, izlazak, dejt",
    goalBreakup: "Raskid",
    goalBreakupDesc: "Prekinuti vezu",
    goalReject: "Odbiti nekoga",
    goalRejectDesc: "Bez povrijeđivanja",
    goalInform: "Saopštiti vijest",
    goalInformDesc: "Lošu informaciju",
    goalApologize: "Izviniti se",
    goalApologizeDesc: "Iskreno, od srca",
    goalNegotiate: "Pregovarati",
    goalNegotiateDesc: "Cijenu, uslove, rokove",
    goalPropose: "Predložiti",
    goalProposeDesc: "Ideju, projekat, saradnju",
    goalFollowup: "Follow-up",
    goalFollowupDesc: "Nastavak razgovora",
    goalAnnounce: "Najaviti",
    goalAnnounceDesc: "Vijest, događaj, promjenu",
    goalThank: "Zahvaliti se",
    goalThankDesc: "Na pomoći, saradnji",
    goalFeedback: "Dati feedback",
    goalFeedbackDesc: "Pozitivno ili konstruktivno",
    goalCustom: "Drugo...",
    goalCustomDesc: "Napiši svoj cilj",
    customGoalPlaceholder: "Opiši šta želiš da postigneš...",
    customGoalHint: "Npr: Želim pozvati kolegu na ručak bez da zvuči kao dejt",
    tonePolite: "Ljubazno",
    tonePoliteDesc: "Prijateljski, toplo",
    toneProfessional: "Profesionalno",
    toneProfessionalDesc: "Jasno, samopouzdano",
    toneDirect: "Direktno",
    toneDirectDesc: "Iskreno, bez okolišanja",
    toneCalm: "Smireno",
    toneCalmDesc: "Kontrolisano, s razumijevanjem",
    tonePlayful: "Zaigrano",
    tonePlayfulDesc: "Šarmantno, duhovito",
    toneFlirty: "Flertovački",
    toneFlirtyDesc: "S podtekstom",
    toneGentle: "Nježno",
    toneGentleDesc: "Obzirno, empatično",
    createAccount: "Napravi nalog",
    enterCredentials: "Unesite vaše podatke za prijavu",
    freeMessages: "Besplatno dobijate 5 poruka",
    wrongCredentials: "Pogrešan email ili lozinka",
    userExists: "Korisnik sa ovim emailom već postoji",
    confirmEmail: "Potvrdite email adresu",
    accountCreated: "Nalog je napravljen. Možete se prijaviti.",
    noAccount: "Nemaš nalog? Registruj se",
    hasAccount: "Već imaš nalog? Prijavi se",
    pleaseWait: "Molimo sačekajte...",
    premium: "Premium",
    messagesLeft: "poruka",
    usedMessages: "Iskorišćeno",
    unlimited: "Neograničene poruke",
    freeLimit: "Besplatno: 5 poruka",
    signInToStart: "Prijavite se da počnete",
    subscribeForUnlimited: "Pretplata za neograničeno",
    limitReached: "Iskoristili ste svih 5 besplatnih poruka.",
    subscribe: "Pretplatite se za neograničeno",
    messageHistory: "Istorija poruka",
    noHistory: "Još nemaš generisanih poruka",
    error: "Greška",
    mustBeSignedIn: "Morate biti prijavljeni za generisanje poruka",
    invalidSession: "Nevalidna sesija. Prijavite se ponovo.",
    errorCheckingLimit: "Greška pri provjeri limita",
    errorGenerating: "Nije moguće generisati poruku. Pokušajte ponovo.",
    tooManyRequests: "Previše zahtjeva. Sačekajte malo i pokušajte ponovo.",
    serviceUnavailable: "Servis trenutno nije dostupan.",
    noResponse: "Nema odgovora od AI servisa",
  },
  mk: {
    appName: "Poruke.AI",
    tagline: "Пишувај подобро, побрзо, полесно",
    signIn: "Најави се",
    signOut: "Одјави се",
    signUp: "Регистрирај се",
    email: "Email",
    password: "Лозинка",
    back: "Назад",
    next: "Понатаму",
    generateMessage: "Генерирај порака",
    signInToGenerate: "Најави се за генерирање",
    newMessage: "Нова порака",
    yourMessage: "Твојата порака",
    copyToClipboard: "Копирај",
    copied: "Копирано!",
    regenerate: "Генерирај повторно",
    generating: "Се генерира порака...",
    loading: "Се вчитува...",
    stepSituation: "Ситуација",
    stepGoal: "Цел",
    stepTone: "Тон",
    stepContext: "Контекст",
    whatIsItAbout: "За што се работи?",
    whatDoYouWantToAchieve: "Што сакаш да постигнеш?",
    howShouldItSound: "Како треба да звучи?",
    describeSituation: "Опиши ја ситуацијата",
    describeContext: "Кратко објасни го контекстот во 1-2 реченици.",
    contextPlaceholder: "Пр: Колегата не ми ги врати парите веќе месец дена, а не знам како да го потсетам без да биде непријатно...",
    situationWork: "Работа",
    situationWorkDesc: "Колеги, шефови, клиенти",
    situationHousing: "Домување",
    situationHousingDesc: "Станодавци, соседи",
    situationPrivate: "Приватно",
    situationPrivateDesc: "Семејство, пријатели",
    situationBuying: "Купопродажба",
    situationBuyingDesc: "Огласи, договори",
    situationLove: "Мување 💕",
    situationLoveDesc: "IG, Messenger, во живо",
    situationBadNews: "Лоши вести",
    situationBadNewsDesc: "Тешки теми, сериозно",
    goalRemind: "Потсети",
    goalRemindDesc: "Некого на нешто",
    goalRefuse: "Одбиј",
    goalRefuseDesc: "Барање или понуда",
    goalAsk: "Замоли",
    goalAskDesc: "За услуга или помош",
    goalCalm: "Смири",
    goalCalmDesc: "Напната ситуација",
    goalClarify: "Разјасни",
    goalClarifyDesc: "Недоразбирање",
    goalOpener: "Започни разговор",
    goalOpenerDesc: "Ice-breaker, прва порака",
    goalFlirt: "Флертувај",
    goalFlirtDesc: "Покажи интерес",
    goalCompliment: "Комплимент",
    goalComplimentDesc: "Оригинален, креативен",
    goalAskOut: "Покани на пиење",
    goalAskOutDesc: "Кафе, излегување, дејт",
    goalBreakup: "Раскинување",
    goalBreakupDesc: "Прекини врска",
    goalReject: "Одбиј некого",
    goalRejectDesc: "Без повредување",
    goalInform: "Соопшти вест",
    goalInformDesc: "Лоша информација",
    goalApologize: "Извини се",
    goalApologizeDesc: "Искрено, од срце",
    goalNegotiate: "Преговарај",
    goalNegotiateDesc: "Цена, услови, рокови",
    goalPropose: "Предложи",
    goalProposeDesc: "Идеја, проект, соработка",
    goalFollowup: "Follow-up",
    goalFollowupDesc: "Продолжување на разговор",
    goalAnnounce: "Најави",
    goalAnnounceDesc: "Вест, настан, промена",
    goalThank: "Заблагодари",
    goalThankDesc: "На помош, соработка",
    goalFeedback: "Дај feedback",
    goalFeedbackDesc: "Позитивно или конструктивно",
    goalCustom: "Друго...",
    goalCustomDesc: "Напиши своја цел",
    customGoalPlaceholder: "Опиши што сакаш да постигнеш...",
    customGoalHint: "Пр: Сакам да поканам колега на ручек без да звучи како дејт",
    tonePolite: "Љубезно",
    tonePoliteDesc: "Пријателски, топло",
    toneProfessional: "Професионално",
    toneProfessionalDesc: "Јасно, самоуверено",
    toneDirect: "Директно",
    toneDirectDesc: "Искрено, без заобиколување",
    toneCalm: "Смирено",
    toneCalmDesc: "Контролирано, со разбирање",
    tonePlayful: "Разиграно",
    tonePlayfulDesc: "Шармантно, духовито",
    toneFlirty: "Флертовачки",
    toneFlirtyDesc: "Со подтекст",
    toneGentle: "Нежно",
    toneGentleDesc: "Обѕирно, емпатично",
    createAccount: "Креирај сметка",
    enterCredentials: "Внесете ги вашите податоци за најава",
    freeMessages: "Бесплатно добивате 5 пораки",
    wrongCredentials: "Погрешен email или лозинка",
    userExists: "Корисник со овој email веќе постои",
    confirmEmail: "Потврдете ја email адресата",
    accountCreated: "Сметката е креирана. Можете да се најавите.",
    noAccount: "Немате сметка? Регистрирајте се",
    hasAccount: "Веќе имате сметка? Најавете се",
    pleaseWait: "Ве молиме почекајте...",
    premium: "Premium",
    messagesLeft: "пораки",
    usedMessages: "Искористено",
    unlimited: "Неограничени пораки",
    freeLimit: "Бесплатно: 5 пораки",
    signInToStart: "Најавете се за да почнете",
    subscribeForUnlimited: "Претплата за неограничено",
    limitReached: "Ги искористивте сите 5 бесплатни пораки.",
    subscribe: "Претплатете се за неограничено",
    messageHistory: "Историја на пораки",
    noHistory: "Сè уште немате генерирани пораки",
    error: "Грешка",
    mustBeSignedIn: "Мора да сте најавени за генерирање пораки",
    invalidSession: "Невалидна сесија. Најавете се повторно.",
    errorCheckingLimit: "Грешка при проверка на лимит",
    errorGenerating: "Не е можно да се генерира порака. Обидете се повторно.",
    tooManyRequests: "Премногу барања. Почекајте малку и обидете се повторно.",
    serviceUnavailable: "Сервисот моментално не е достапен.",
    noResponse: "Нема одговор од AI сервисот",
  },
  sl: {
    appName: "Poruke.AI",
    tagline: "Piši bolje, hitreje, lažje",
    signIn: "Prijava",
    signOut: "Odjava",
    signUp: "Registracija",
    email: "Email",
    password: "Geslo",
    back: "Nazaj",
    next: "Naprej",
    generateMessage: "Generiraj sporočilo",
    signInToGenerate: "Prijavi se za generiranje",
    newMessage: "Novo sporočilo",
    yourMessage: "Tvoje sporočilo",
    copyToClipboard: "Kopiraj",
    copied: "Kopirano!",
    regenerate: "Generiraj ponovno",
    generating: "Generiranje sporočila...",
    loading: "Nalaganje...",
    stepSituation: "Situacija",
    stepGoal: "Cilj",
    stepTone: "Ton",
    stepContext: "Kontekst",
    whatIsItAbout: "Za kaj gre?",
    whatDoYouWantToAchieve: "Kaj želiš doseči?",
    howShouldItSound: "Kako naj zveni?",
    describeSituation: "Opiši situacijo",
    describeContext: "Na kratko pojasni kontekst v 1-2 stavkih.",
    contextPlaceholder: "Npr: Kolega mi že mesec dni ni vrnil denarja, ne vem pa, kako ga opomniti, da ne bo neprijetno...",
    situationWork: "Delo",
    situationWorkDesc: "Kolegi, šefi, stranke",
    situationHousing: "Stanovanje",
    situationHousingDesc: "Najemodajalci, sosedje",
    situationPrivate: "Zasebno",
    situationPrivateDesc: "Družina, prijatelji",
    situationBuying: "Nakup/prodaja",
    situationBuyingDesc: "Oglasi, dogovori",
    situationLove: "Zapeljevanje 💕",
    situationLoveDesc: "IG, Messenger, v živo",
    situationBadNews: "Slabe novice",
    situationBadNewsDesc: "Težke teme, resno",
    goalRemind: "Opomniti",
    goalRemindDesc: "Nekoga na nekaj",
    goalRefuse: "Zavrniti",
    goalRefuseDesc: "Prošnjo ali ponudbo",
    goalAsk: "Prositi",
    goalAskDesc: "Za uslugo ali pomoč",
    goalCalm: "Pomiriti",
    goalCalmDesc: "Napeto situacijo",
    goalClarify: "Razjasniti",
    goalClarifyDesc: "Nesporazum",
    goalOpener: "Začeti pogovor",
    goalOpenerDesc: "Ice-breaker, prvo sporočilo",
    goalFlirt: "Flirtati",
    goalFlirtDesc: "Pokazati zanimanje",
    goalCompliment: "Kompliment",
    goalComplimentDesc: "Originalen, kreativen",
    goalAskOut: "Povabiti na pijačo",
    goalAskOutDesc: "Kavo, zmenek, dejt",
    goalBreakup: "Prekinitev",
    goalBreakupDesc: "Prekiniti razmerje",
    goalReject: "Zavrniti nekoga",
    goalRejectDesc: "Brez prizadetja",
    goalInform: "Sporočiti novico",
    goalInformDesc: "Slabo informacijo",
    goalApologize: "Opravičiti se",
    goalApologizeDesc: "Iskreno, od srca",
    goalNegotiate: "Pogajati se",
    goalNegotiateDesc: "Ceno, pogoje, roke",
    goalPropose: "Predlagati",
    goalProposeDesc: "Idejo, projekt, sodelovanje",
    goalFollowup: "Follow-up",
    goalFollowupDesc: "Nadaljevanje pogovora",
    goalAnnounce: "Napovedati",
    goalAnnounceDesc: "Novico, dogodek, spremembo",
    goalThank: "Zahvaliti se",
    goalThankDesc: "Za pomoč, sodelovanje",
    goalFeedback: "Dati feedback",
    goalFeedbackDesc: "Pozitivno ali konstruktivno",
    goalCustom: "Drugo...",
    goalCustomDesc: "Napiši svoj cilj",
    customGoalPlaceholder: "Opiši, kaj želiš doseči...",
    customGoalHint: "Npr: Želim povabiti kolega na kosilo brez da zveni kot zmenek",
    tonePolite: "Vljudno",
    tonePoliteDesc: "Prijazno, toplo",
    toneProfessional: "Profesionalno",
    toneProfessionalDesc: "Jasno, samozavestno",
    toneDirect: "Neposredno",
    toneDirectDesc: "Iskreno, brez ovijanja",
    toneCalm: "Umirjeno",
    toneCalmDesc: "Kontrolirano, z razumevanjem",
    tonePlayful: "Igrivo",
    tonePlayfulDesc: "Šarmantno, duhovito",
    toneFlirty: "Flirtovsko",
    toneFlirtyDesc: "Z namigom",
    toneGentle: "Nežno",
    toneGentleDesc: "Obzirno, empatično",
    createAccount: "Ustvari račun",
    enterCredentials: "Vnesite svoje podatke za prijavo",
    freeMessages: "Brezplačno dobite 5 sporočil",
    wrongCredentials: "Napačen email ali geslo",
    userExists: "Uporabnik s tem emailom že obstaja",
    confirmEmail: "Potrdite email naslov",
    accountCreated: "Račun je ustvarjen. Lahko se prijavite.",
    noAccount: "Nimate računa? Registrirajte se",
    hasAccount: "Že imate račun? Prijavite se",
    pleaseWait: "Prosim počakajte...",
    premium: "Premium",
    messagesLeft: "sporočil",
    usedMessages: "Porabljeno",
    unlimited: "Neomejeno sporočil",
    freeLimit: "Brezplačno: 5 sporočil",
    signInToStart: "Prijavite se za začetek",
    subscribeForUnlimited: "Naročnina za neomejeno",
    limitReached: "Porabili ste vseh 5 brezplačnih sporočil.",
    subscribe: "Naročite se za neomejeno",
    messageHistory: "Zgodovina sporočil",
    noHistory: "Še nimate generiranih sporočil",
    error: "Napaka",
    mustBeSignedIn: "Za generiranje sporočil morate biti prijavljeni",
    invalidSession: "Neveljavna seja. Prijavite se ponovno.",
    errorCheckingLimit: "Napaka pri preverjanju limita",
    errorGenerating: "Sporočila ni mogoče generirati. Poskusite znova.",
    tooManyRequests: "Preveč zahtev. Počakajte malo in poskusite znova.",
    serviceUnavailable: "Storitev trenutno ni na voljo.",
    noResponse: "Ni odgovora od AI storitve",
  },
  en: {
    appName: "Poruke.AI",
    tagline: "Write better, faster, easier",
    signIn: "Sign in",
    signOut: "Sign out",
    signUp: "Sign up",
    email: "Email",
    password: "Password",
    back: "Back",
    next: "Next",
    generateMessage: "Generate message",
    signInToGenerate: "Sign in to generate",
    newMessage: "New message",
    yourMessage: "Your message",
    copyToClipboard: "Copy",
    copied: "Copied!",
    regenerate: "Regenerate",
    generating: "Generating message...",
    loading: "Loading...",
    stepSituation: "Situation",
    stepGoal: "Goal",
    stepTone: "Tone",
    stepContext: "Context",
    whatIsItAbout: "What is it about?",
    whatDoYouWantToAchieve: "What do you want to achieve?",
    howShouldItSound: "How should it sound?",
    describeSituation: "Describe the situation",
    describeContext: "Briefly explain the context in 1-2 sentences.",
    contextPlaceholder: "E.g.: My colleague hasn't returned the money for a month, and I don't know how to remind them without it being awkward...",
    situationWork: "Work",
    situationWorkDesc: "Colleagues, bosses, clients",
    situationHousing: "Housing",
    situationHousingDesc: "Landlords, neighbors",
    situationPrivate: "Personal",
    situationPrivateDesc: "Family, friends",
    situationBuying: "Buying/Selling",
    situationBuyingDesc: "Listings, deals",
    situationLove: "Dating 💕",
    situationLoveDesc: "IG, Messenger, in person",
    situationBadNews: "Bad news",
    situationBadNewsDesc: "Tough topics, serious",
    goalRemind: "Remind",
    goalRemindDesc: "Someone about something",
    goalRefuse: "Refuse",
    goalRefuseDesc: "A request or offer",
    goalAsk: "Ask",
    goalAskDesc: "For a favor or help",
    goalCalm: "Calm down",
    goalCalmDesc: "A tense situation",
    goalClarify: "Clarify",
    goalClarifyDesc: "A misunderstanding",
    goalOpener: "Start a conversation",
    goalOpenerDesc: "Ice-breaker, first message",
    goalFlirt: "Flirt",
    goalFlirtDesc: "Show interest",
    goalCompliment: "Compliment",
    goalComplimentDesc: "Original, creative",
    goalAskOut: "Ask out",
    goalAskOutDesc: "Coffee, date, hangout",
    goalBreakup: "Break up",
    goalBreakupDesc: "End a relationship",
    goalReject: "Reject someone",
    goalRejectDesc: "Without hurting them",
    goalInform: "Deliver news",
    goalInformDesc: "Bad information",
    goalApologize: "Apologize",
    goalApologizeDesc: "Sincerely, from the heart",
    goalNegotiate: "Negotiate",
    goalNegotiateDesc: "Price, terms, deadlines",
    goalPropose: "Propose",
    goalProposeDesc: "An idea, project, collaboration",
    goalFollowup: "Follow up",
    goalFollowupDesc: "Continue the conversation",
    goalAnnounce: "Announce",
    goalAnnounceDesc: "News, event, change",
    goalThank: "Thank",
    goalThankDesc: "For help, collaboration",
    goalFeedback: "Give feedback",
    goalFeedbackDesc: "Positive or constructive",
    goalCustom: "Other...",
    goalCustomDesc: "Write your own goal",
    customGoalPlaceholder: "Describe what you want to achieve...",
    customGoalHint: "E.g.: I want to invite a colleague to lunch without it sounding like a date",
    tonePolite: "Polite",
    tonePoliteDesc: "Friendly, warm",
    toneProfessional: "Professional",
    toneProfessionalDesc: "Clear, confident",
    toneDirect: "Direct",
    toneDirectDesc: "Honest, no beating around the bush",
    toneCalm: "Calm",
    toneCalmDesc: "Controlled, understanding",
    tonePlayful: "Playful",
    tonePlayfulDesc: "Charming, witty",
    toneFlirty: "Flirty",
    toneFlirtyDesc: "With subtext",
    toneGentle: "Gentle",
    toneGentleDesc: "Considerate, empathetic",
    createAccount: "Create account",
    enterCredentials: "Enter your credentials to sign in",
    freeMessages: "You get 5 free messages",
    wrongCredentials: "Wrong email or password",
    userExists: "A user with this email already exists",
    confirmEmail: "Confirm your email address",
    accountCreated: "Account created. You can now sign in.",
    noAccount: "Don't have an account? Sign up",
    hasAccount: "Already have an account? Sign in",
    pleaseWait: "Please wait...",
    premium: "Premium",
    messagesLeft: "messages",
    usedMessages: "Used",
    unlimited: "Unlimited messages",
    freeLimit: "Free: 5 messages",
    signInToStart: "Sign in to get started",
    subscribeForUnlimited: "Subscribe for unlimited",
    limitReached: "You've used all 5 free messages.",
    subscribe: "Subscribe for unlimited",
    messageHistory: "Message history",
    noHistory: "You don't have any generated messages yet",
    error: "Error",
    mustBeSignedIn: "You must be signed in to generate messages",
    invalidSession: "Invalid session. Please sign in again.",
    errorCheckingLimit: "Error checking limit",
    errorGenerating: "Unable to generate message. Please try again.",
    tooManyRequests: "Too many requests. Wait a moment and try again.",
    serviceUnavailable: "Service currently unavailable.",
    noResponse: "No response from AI service",
  },
  ru: {
    appName: "Poruke.AI",
    tagline: "Пиши лучше, быстрее, проще",
    signIn: "Войти",
    signOut: "Выйти",
    signUp: "Регистрация",
    email: "Email",
    password: "Пароль",
    back: "Назад",
    next: "Далее",
    generateMessage: "Сгенерировать сообщение",
    signInToGenerate: "Войдите для генерации",
    newMessage: "Новое сообщение",
    yourMessage: "Ваше сообщение",
    copyToClipboard: "Копировать",
    copied: "Скопировано!",
    regenerate: "Сгенерировать заново",
    generating: "Генерируется сообщение...",
    loading: "Загрузка...",
    stepSituation: "Ситуация",
    stepGoal: "Цель",
    stepTone: "Тон",
    stepContext: "Контекст",
    whatIsItAbout: "О чём речь?",
    whatDoYouWantToAchieve: "Чего вы хотите добиться?",
    howShouldItSound: "Как должно звучать?",
    describeSituation: "Опишите ситуацию",
    describeContext: "Кратко объясните контекст в 1-2 предложениях.",
    contextPlaceholder: "Напр.: Коллега не возвращает деньги уже месяц, а я не знаю, как напомнить, чтобы не было неловко...",
    situationWork: "Работа",
    situationWorkDesc: "Коллеги, начальство, клиенты",
    situationHousing: "Жильё",
    situationHousingDesc: "Арендодатели, соседи",
    situationPrivate: "Личное",
    situationPrivateDesc: "Семья, друзья",
    situationBuying: "Купля-продажа",
    situationBuyingDesc: "Объявления, сделки",
    situationLove: "Флирт 💕",
    situationLoveDesc: "IG, Messenger, вживую",
    situationBadNews: "Плохие новости",
    situationBadNewsDesc: "Тяжёлые темы, серьёзно",
    goalRemind: "Напомнить",
    goalRemindDesc: "Кому-то о чём-то",
    goalRefuse: "Отказать",
    goalRefuseDesc: "В просьбе или предложении",
    goalAsk: "Попросить",
    goalAskDesc: "Об услуге или помощи",
    goalCalm: "Успокоить",
    goalCalmDesc: "Напряжённую ситуацию",
    goalClarify: "Прояснить",
    goalClarifyDesc: "Недоразумение",
    goalOpener: "Начать разговор",
    goalOpenerDesc: "Первое сообщение",
    goalFlirt: "Пофлиртовать",
    goalFlirtDesc: "Показать интерес",
    goalCompliment: "Комплимент",
    goalComplimentDesc: "Оригинальный, креативный",
    goalAskOut: "Пригласить на свидание",
    goalAskOutDesc: "Кофе, прогулка, встреча",
    goalBreakup: "Расставание",
    goalBreakupDesc: "Прекратить отношения",
    goalReject: "Отвергнуть кого-то",
    goalRejectDesc: "Без обид",
    goalInform: "Сообщить новость",
    goalInformDesc: "Плохую информацию",
    goalApologize: "Извиниться",
    goalApologizeDesc: "Искренне, от души",
    goalNegotiate: "Договориться",
    goalNegotiateDesc: "О цене, условиях, сроках",
    goalPropose: "Предложить",
    goalProposeDesc: "Идею, проект, сотрудничество",
    goalFollowup: "Напомнить о себе",
    goalFollowupDesc: "Продолжить разговор",
    goalAnnounce: "Объявить",
    goalAnnounceDesc: "Новость, событие, изменение",
    goalThank: "Поблагодарить",
    goalThankDesc: "За помощь, сотрудничество",
    goalFeedback: "Дать отзыв",
    goalFeedbackDesc: "Положительный или конструктивный",
    goalCustom: "Другое...",
    goalCustomDesc: "Напишите свою цель",
    customGoalPlaceholder: "Опишите, чего хотите добиться...",
    customGoalHint: "Напр.: Хочу пригласить коллегу на обед, чтобы это не звучало как свидание",
    tonePolite: "Вежливо",
    tonePoliteDesc: "Дружелюбно, тепло",
    toneProfessional: "Профессионально",
    toneProfessionalDesc: "Чётко, уверенно",
    toneDirect: "Прямо",
    toneDirectDesc: "Честно, без уловок",
    toneCalm: "Спокойно",
    toneCalmDesc: "Сдержанно, с пониманием",
    tonePlayful: "Игриво",
    tonePlayfulDesc: "Обаятельно, с юмором",
    toneFlirty: "Кокетливо",
    toneFlirtyDesc: "С подтекстом",
    toneGentle: "Мягко",
    toneGentleDesc: "Деликатно, с эмпатией",
    createAccount: "Создать аккаунт",
    enterCredentials: "Введите данные для входа",
    freeMessages: "Вы получаете 5 бесплатных сообщений",
    wrongCredentials: "Неверный email или пароль",
    userExists: "Пользователь с таким email уже существует",
    confirmEmail: "Подтвердите email адрес",
    accountCreated: "Аккаунт создан. Можете войти.",
    noAccount: "Нет аккаунта? Зарегистрируйтесь",
    hasAccount: "Уже есть аккаунт? Войдите",
    pleaseWait: "Пожалуйста, подождите...",
    premium: "Премиум",
    messagesLeft: "сообщений",
    usedMessages: "Использовано",
    unlimited: "Безлимитные сообщения",
    freeLimit: "Бесплатно: 5 сообщений",
    signInToStart: "Войдите, чтобы начать",
    subscribeForUnlimited: "Подписка для безлимита",
    limitReached: "Вы использовали все 5 бесплатных сообщений.",
    subscribe: "Подпишитесь для безлимита",
    messageHistory: "История сообщений",
    noHistory: "У вас пока нет сгенерированных сообщений",
    error: "Ошибка",
    mustBeSignedIn: "Для генерации сообщений нужно войти в систему",
    invalidSession: "Недействительная сессия. Войдите снова.",
    errorCheckingLimit: "Ошибка при проверке лимита",
    errorGenerating: "Не удалось сгенерировать сообщение. Попробуйте ещё раз.",
    tooManyRequests: "Слишком много запросов. Подождите немного и попробуйте снова.",
    serviceUnavailable: "Сервис временно недоступен.",
    noResponse: "Нет ответа от AI сервиса",
  },
  uk: {
    appName: "Poruke.AI",
    tagline: "Пиши краще, швидше, легше",
    signIn: "Увійти",
    signOut: "Вийти",
    signUp: "Реєстрація",
    email: "Email",
    password: "Пароль",
    back: "Назад",
    next: "Далі",
    generateMessage: "Згенерувати повідомлення",
    signInToGenerate: "Увійдіть для генерації",
    newMessage: "Нове повідомлення",
    yourMessage: "Ваше повідомлення",
    copyToClipboard: "Копіювати",
    copied: "Скопійовано!",
    regenerate: "Згенерувати знову",
    generating: "Генерується повідомлення...",
    loading: "Завантаження...",
    stepSituation: "Ситуація",
    stepGoal: "Ціль",
    stepTone: "Тон",
    stepContext: "Контекст",
    whatIsItAbout: "Про що йдеться?",
    whatDoYouWantToAchieve: "Чого ви хочете досягти?",
    howShouldItSound: "Як має звучати?",
    describeSituation: "Опишіть ситуацію",
    describeContext: "Коротко поясніть контекст в 1-2 реченнях.",
    contextPlaceholder: "Напр.: Колега не повертає гроші вже місяць, і я не знаю, як нагадати, щоб не було незручно...",
    situationWork: "Робота",
    situationWorkDesc: "Колеги, керівництво, клієнти",
    situationHousing: "Житло",
    situationHousingDesc: "Орендодавці, сусіди",
    situationPrivate: "Особисте",
    situationPrivateDesc: "Сім'я, друзі",
    situationBuying: "Купівля-продаж",
    situationBuyingDesc: "Оголошення, угоди",
    situationLove: "Флірт 💕",
    situationLoveDesc: "IG, Messenger, наживо",
    situationBadNews: "Погані новини",
    situationBadNewsDesc: "Важкі теми, серйозно",
    goalRemind: "Нагадати",
    goalRemindDesc: "Комусь про щось",
    goalRefuse: "Відмовити",
    goalRefuseDesc: "У проханні або пропозиції",
    goalAsk: "Попросити",
    goalAskDesc: "Про послугу або допомогу",
    goalCalm: "Заспокоїти",
    goalCalmDesc: "Напружену ситуацію",
    goalClarify: "З'ясувати",
    goalClarifyDesc: "Непорозуміння",
    goalOpener: "Почати розмову",
    goalOpenerDesc: "Перше повідомлення",
    goalFlirt: "Пофліртувати",
    goalFlirtDesc: "Показати зацікавленість",
    goalCompliment: "Комплімент",
    goalComplimentDesc: "Оригінальний, креативний",
    goalAskOut: "Запросити на побачення",
    goalAskOutDesc: "Кава, прогулянка, зустріч",
    goalBreakup: "Розставання",
    goalBreakupDesc: "Припинити стосунки",
    goalReject: "Відхилити когось",
    goalRejectDesc: "Без образ",
    goalInform: "Повідомити новину",
    goalInformDesc: "Погану інформацію",
    goalApologize: "Вибачитися",
    goalApologizeDesc: "Щиро, від серця",
    goalNegotiate: "Домовитися",
    goalNegotiateDesc: "Про ціну, умови, терміни",
    goalPropose: "Запропонувати",
    goalProposeDesc: "Ідею, проєкт, співпрацю",
    goalFollowup: "Нагадати про себе",
    goalFollowupDesc: "Продовжити розмову",
    goalAnnounce: "Оголосити",
    goalAnnounceDesc: "Новину, подію, зміну",
    goalThank: "Подякувати",
    goalThankDesc: "За допомогу, співпрацю",
    goalFeedback: "Дати відгук",
    goalFeedbackDesc: "Позитивний або конструктивний",
    goalCustom: "Інше...",
    goalCustomDesc: "Напишіть свою ціль",
    customGoalPlaceholder: "Опишіть, чого хочете досягти...",
    customGoalHint: "Напр.: Хочу запросити колегу на обід, щоб це не звучало як побачення",
    tonePolite: "Ввічливо",
    tonePoliteDesc: "Привітно, тепло",
    toneProfessional: "Професійно",
    toneProfessionalDesc: "Чітко, впевнено",
    toneDirect: "Прямо",
    toneDirectDesc: "Чесно, без натяків",
    toneCalm: "Спокійно",
    toneCalmDesc: "Стримано, з розумінням",
    tonePlayful: "Грайливо",
    tonePlayfulDesc: "Чарівно, з гумором",
    toneFlirty: "Кокетливо",
    toneFlirtyDesc: "З підтекстом",
    toneGentle: "М'яко",
    toneGentleDesc: "Делікатно, з емпатією",
    createAccount: "Створити акаунт",
    enterCredentials: "Введіть дані для входу",
    freeMessages: "Ви отримуєте 5 безкоштовних повідомлень",
    wrongCredentials: "Невірний email або пароль",
    userExists: "Користувач з таким email вже існує",
    confirmEmail: "Підтвердіть email адресу",
    accountCreated: "Акаунт створено. Можете увійти.",
    noAccount: "Немає акаунту? Зареєструйтесь",
    hasAccount: "Вже є акаунт? Увійдіть",
    pleaseWait: "Будь ласка, зачекайте...",
    premium: "Преміум",
    messagesLeft: "повідомлень",
    usedMessages: "Використано",
    unlimited: "Безлімітні повідомлення",
    freeLimit: "Безкоштовно: 5 повідомлень",
    signInToStart: "Увійдіть, щоб почати",
    subscribeForUnlimited: "Підписка для безліміту",
    limitReached: "Ви використали всі 5 безкоштовних повідомлень.",
    subscribe: "Підпишіться для безліміту",
    messageHistory: "Історія повідомлень",
    noHistory: "У вас поки немає згенерованих повідомлень",
    error: "Помилка",
    mustBeSignedIn: "Для генерації повідомлень потрібно увійти в систему",
    invalidSession: "Недійсна сесія. Увійдіть знову.",
    errorCheckingLimit: "Помилка при перевірці ліміту",
    errorGenerating: "Не вдалося згенерувати повідомлення. Спробуйте ще раз.",
    tooManyRequests: "Забагато запитів. Зачекайте трохи і спробуйте знову.",
    serviceUnavailable: "Сервіс тимчасово недоступний.",
    noResponse: "Немає відповіді від AI сервісу",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  languageInfo: LanguageInfo;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);
const STORAGE_KEY = "poruke-language";

function detectBrowserLanguage(): Language {
  const browserLangs = navigator.languages || [navigator.language];
  const langMap: Record<string, Language> = {
    sr: "sr", hr: "hr", bs: "bs", mk: "mk", sl: "sl",
    en: "en", ru: "ru", uk: "uk",
  };
  for (const bl of browserLangs) {
    const code = bl.toLowerCase().split("-")[0];
    if (code === "cnr") return "me";
    if (langMap[code]) return langMap[code];
  }
  return "sr";
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem(STORAGE_KEY);
    if (saved && languages.some(l => l.code === saved)) return saved as Language;
    return detectBrowserLanguage();
  });

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.sr[key] || key;
  };

  const languageInfo = languages.find(l => l.code === language) || languages[0];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languageInfo }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
