import { createContext, useContext, useState, ReactNode, useEffect } from "react";

export type Language = "sr" | "hr" | "bs" | "me" | "mk" | "sl";

export interface LanguageInfo {
  code: Language;
  name: string;
  nativeName: string;
  flag: string;
}

export const languages: LanguageInfo[] = [
  { code: "sr", name: "Serbian", nativeName: "Srpski", flag: "🇷🇸" },
  { code: "hr", name: "Croatian", nativeName: "Hrvatski", flag: "🇭🇷" },
  { code: "bs", name: "Bosnian", nativeName: "Bosanski", flag: "🇧🇦" },
  { code: "me", name: "Montenegrin", nativeName: "Crnogorski", flag: "🇲🇪" },
  { code: "mk", name: "Macedonian", nativeName: "Македонски", flag: "🇲🇰" },
  { code: "sl", name: "Slovenian", nativeName: "Slovenščina", flag: "🇸🇮" },
];

// UI translations for each language
export const translations: Record<Language, Record<string, string>> = {
  sr: {
    appName: "Poruke.AI",
    tagline: "Piši bolje, brže, lakše",
    signIn: "Prijavi se",
    signOut: "Odjavi se",
    signUp: "Registruj se",
    email: "Email",
    password: "Lozinka",
    back: "Nazad",
    next: "Dalje",
    generateMessage: "Generiši poruku",
    signInToGenerate: "Prijavi se da generišeš",
    newMessage: "Nova poruka",
    yourMessage: "Tvoja poruka",
    copyToClipboard: "Kopiraj",
    copied: "Kopirano!",
    regenerate: "Generiši ponovo",
    generating: "Generiše se poruka...",
    loading: "Učitavanje...",
    stepSituation: "Situacija",
    stepGoal: "Cilj",
    stepTone: "Ton",
    stepContext: "Kontekst",
    whatIsItAbout: "O čemu se radi?",
    whatDoYouWantToAchieve: "Šta želiš da postigneš?",
    howShouldItSound: "Kako da zvuči?",
    describeSituation: "Opiši situaciju",
    describeContext: "Kratko objasni kontekst u 1-2 rečenice.",
    contextPlaceholder: "Npr: Kolega mi nije vratio novac već mesec dana, a ne znam kako da ga podsetim a da ne bude neprijatno...",
    situationWork: "Posao",
    situationWorkDesc: "Kolege, šefovi, klijenti",
    situationHousing: "Stanovanje",
    situationHousingDesc: "Stanodavci, komšije",
    situationPrivate: "Privatno",
    situationPrivateDesc: "Porodica, prijatelji",
    situationBuying: "Kupoprodaja",
    situationBuyingDesc: "Oglasi, dogovori",
    situationLove: "Muvanje 💕",
    situationLoveDesc: "IG, Messenger, uživo",
    situationBadNews: "Loše vesti",
    situationBadNewsDesc: "Teške teme, ozbiljno",
    goalRemind: "Podsetiti",
    goalRemindDesc: "Nekoga na nešto",
    goalRefuse: "Odbiti",
    goalRefuseDesc: "Zahtev ili ponudu",
    goalAsk: "Zamoliti",
    goalAskDesc: "Za uslugu ili pomoć",
    goalCalm: "Smiriti",
    goalCalmDesc: "Napetu situaciju",
    goalClarify: "Razjasniti",
    goalClarifyDesc: "Nesporazum",
    goalOpener: "Započeti razgovor",
    goalOpenerDesc: "Ice-breaker, prva poruka",
    goalFlirt: "Flertovati",
    goalFlirtDesc: "Pokazati interesovanje",
    goalCompliment: "Kompliment",
    goalComplimentDesc: "Originalan, kreativan",
    goalAskOut: "Pozvati na piće",
    goalAskOutDesc: "Kafu, izlazak, dejt",
    goalBreakup: "Raskid",
    goalBreakupDesc: "Prekinuti vezu",
    goalReject: "Odbiti nekoga",
    goalRejectDesc: "Bez povređivanja",
    goalInform: "Saopštiti vest",
    goalInformDesc: "Lošu informaciju",
    goalApologize: "Izviniti se",
    goalApologizeDesc: "Iskreno, od srca",
    tonePolite: "Ljubazno",
    tonePoliteDesc: "Prijateljski, toplo",
    toneProfessional: "Profesionalno",
    toneProfessionalDesc: "Jasno, samouvereno",
    toneDirect: "Direktno",
    toneDirectDesc: "Iskreno, bez okolišanja",
    toneCalm: "Smireno",
    toneCalmDesc: "Kontrolisano, sa razumevanjem",
    tonePlayful: "Zaigrano",
    tonePlayfulDesc: "Šarmantno, duhovito",
    toneFlirty: "Flertovački",
    toneFlirtyDesc: "Sa podtekstom",
    toneGentle: "Nežno",
    toneGentleDesc: "Obzirno, empatično",
    createAccount: "Kreiraj nalog",
    enterCredentials: "Unesite vaše podatke za prijavu",
    freeMessages: "Besplatno dobijate 5 poruka",
    wrongCredentials: "Pogrešan email ili lozinka",
    userExists: "Korisnik sa ovim emailom već postoji",
    confirmEmail: "Potvrdite email adresu",
    accountCreated: "Nalog je kreiran. Možete se prijaviti.",
    noAccount: "Nemate nalog? Registrujte se",
    hasAccount: "Već imate nalog? Prijavite se",
    pleaseWait: "Molimo sačekajte...",
    premium: "Premium",
    messagesLeft: "poruka",
    usedMessages: "Iskorišćeno",
    unlimited: "Neograničene poruke",
    freeLimit: "Besplatno: 5 poruka",
    signInToStart: "Prijavite se da počnete",
    subscribeForUnlimited: "Pretplata za neograničeno",
    limitReached: "Iskoristili ste svih 5 besplatnih poruka.",
    subscribe: "Pretplatite se za neograničeno",
    messageHistory: "Istorija poruka",
    noHistory: "Još nemate generisanih poruka",
    error: "Greška",
    mustBeSignedIn: "Morate biti prijavljeni da biste generisali poruke",
    invalidSession: "Nevalidna sesija. Prijavite se ponovo.",
    errorCheckingLimit: "Greška pri proveri limita",
    errorGenerating: "Nije moguće generisati poruku. Pokušajte ponovo.",
    tooManyRequests: "Previše zahteva. Sačekajte malo i pokušajte ponovo.",
    serviceUnavailable: "Servis trenutno nije dostupan.",
    noResponse: "Nema odgovora od AI servisa",
  },
  hr: {
    appName: "Poruke.AI",
    tagline: "Piši bolje, brže, lakše",
    signIn: "Prijavi se",
    signOut: "Odjavi se",
    signUp: "Registriraj se",
    email: "Email",
    password: "Lozinka",
    back: "Natrag",
    next: "Dalje",
    generateMessage: "Generiraj poruku",
    signInToGenerate: "Prijavi se za generiranje",
    newMessage: "Nova poruka",
    yourMessage: "Tvoja poruka",
    copyToClipboard: "Kopiraj",
    copied: "Kopirano!",
    regenerate: "Generiraj ponovo",
    generating: "Generira se poruka...",
    loading: "Učitavanje...",
    stepSituation: "Situacija",
    stepGoal: "Cilj",
    stepTone: "Ton",
    stepContext: "Kontekst",
    whatIsItAbout: "O čemu se radi?",
    whatDoYouWantToAchieve: "Što želiš postići?",
    howShouldItSound: "Kako treba zvučati?",
    describeSituation: "Opiši situaciju",
    describeContext: "Ukratko objasni kontekst u 1-2 rečenice.",
    contextPlaceholder: "Npr: Kolega mi nije vratio novac već mjesec dana, a ne znam kako ga podsjetiti, a da ne bude neugodno...",
    situationWork: "Posao",
    situationWorkDesc: "Kolege, šefovi, klijenti",
    situationHousing: "Stanovanje",
    situationHousingDesc: "Stanodavci, susjedi",
    situationPrivate: "Privatno",
    situationPrivateDesc: "Obitelj, prijatelji",
    situationBuying: "Kupoprodaja",
    situationBuyingDesc: "Oglasi, dogovori",
    situationLove: "Muvanje 💕",
    situationLoveDesc: "IG, Messenger, uživo",
    situationBadNews: "Loše vijesti",
    situationBadNewsDesc: "Teške teme, ozbiljno",
    goalRemind: "Podsjetiti",
    goalRemindDesc: "Nekoga na nešto",
    goalRefuse: "Odbiti",
    goalRefuseDesc: "Zahtjev ili ponudu",
    goalAsk: "Zamoliti",
    goalAskDesc: "Za uslugu ili pomoć",
    goalCalm: "Smiriti",
    goalCalmDesc: "Napetu situaciju",
    goalClarify: "Razjasniti",
    goalClarifyDesc: "Nesporazum",
    goalOpener: "Započeti razgovor",
    goalOpenerDesc: "Ice-breaker, prva poruka",
    goalFlirt: "Flertati",
    goalFlirtDesc: "Pokazati interes",
    goalCompliment: "Kompliment",
    goalComplimentDesc: "Originalan, kreativan",
    goalAskOut: "Pozvati na piće",
    goalAskOutDesc: "Kavu, izlazak, dejt",
    goalBreakup: "Prekid",
    goalBreakupDesc: "Prekinuti vezu",
    goalReject: "Odbiti nekoga",
    goalRejectDesc: "Bez povrijeđivanja",
    goalInform: "Priopćiti vijest",
    goalInformDesc: "Lošu informaciju",
    goalApologize: "Ispričati se",
    goalApologizeDesc: "Iskreno, od srca",
    tonePolite: "Ljubazno",
    tonePoliteDesc: "Prijateljski, toplo",
    toneProfessional: "Profesionalno",
    toneProfessionalDesc: "Jasno, samouvjereno",
    toneDirect: "Direktno",
    toneDirectDesc: "Iskreno, bez okolišanja",
    toneCalm: "Smireno",
    toneCalmDesc: "Kontrolirano, s razumijevanjem",
    tonePlayful: "Zaigrano",
    tonePlayfulDesc: "Šarmantno, duhovito",
    toneFlirty: "Flertovački",
    toneFlirtyDesc: "S podtekstom",
    toneGentle: "Nježno",
    toneGentleDesc: "Obzirno, empatično",
    createAccount: "Kreiraj račun",
    enterCredentials: "Unesite vaše podatke za prijavu",
    freeMessages: "Besplatno dobivate 5 poruka",
    wrongCredentials: "Pogrešan email ili lozinka",
    userExists: "Korisnik s ovim emailom već postoji",
    confirmEmail: "Potvrdite email adresu",
    accountCreated: "Račun je kreiran. Možete se prijaviti.",
    noAccount: "Nemate račun? Registrirajte se",
    hasAccount: "Već imate račun? Prijavite se",
    pleaseWait: "Molimo pričekajte...",
    premium: "Premium",
    messagesLeft: "poruka",
    usedMessages: "Iskorišteno",
    unlimited: "Neograničene poruke",
    freeLimit: "Besplatno: 5 poruka",
    signInToStart: "Prijavite se za početak",
    subscribeForUnlimited: "Pretplata za neograničeno",
    limitReached: "Iskoristili ste svih 5 besplatnih poruka.",
    subscribe: "Pretplatite se za neograničeno",
    messageHistory: "Povijest poruka",
    noHistory: "Još nemate generiranih poruka",
    error: "Greška",
    mustBeSignedIn: "Morate biti prijavljeni za generiranje poruka",
    invalidSession: "Nevalidna sesija. Prijavite se ponovo.",
    errorCheckingLimit: "Greška pri provjeri limita",
    errorGenerating: "Nije moguće generirati poruku. Pokušajte ponovo.",
    tooManyRequests: "Previše zahtjeva. Pričekajte malo i pokušajte ponovo.",
    serviceUnavailable: "Servis trenutno nije dostupan.",
    noResponse: "Nema odgovora od AI servisa",
  },
  bs: {
    appName: "Poruke.AI",
    tagline: "Piši bolje, brže, lakše",
    signIn: "Prijavi se",
    signOut: "Odjavi se",
    signUp: "Registruj se",
    email: "Email",
    password: "Lozinka",
    back: "Nazad",
    next: "Dalje",
    generateMessage: "Generiši poruku",
    signInToGenerate: "Prijavi se za generisanje",
    newMessage: "Nova poruka",
    yourMessage: "Tvoja poruka",
    copyToClipboard: "Kopiraj",
    copied: "Kopirano!",
    regenerate: "Generiši ponovo",
    generating: "Generiše se poruka...",
    loading: "Učitavanje...",
    stepSituation: "Situacija",
    stepGoal: "Cilj",
    stepTone: "Ton",
    stepContext: "Kontekst",
    whatIsItAbout: "O čemu se radi?",
    whatDoYouWantToAchieve: "Šta želiš postići?",
    howShouldItSound: "Kako da zvuči?",
    describeSituation: "Opiši situaciju",
    describeContext: "Ukratko objasni kontekst u 1-2 rečenice.",
    contextPlaceholder: "Npr: Kolega mi nije vratio novac već mjesec dana, a ne znam kako da ga podsjetim a da ne bude neprijatno...",
    situationWork: "Posao",
    situationWorkDesc: "Kolege, šefovi, klijenti",
    situationHousing: "Stanovanje",
    situationHousingDesc: "Stanodavci, komšije",
    situationPrivate: "Privatno",
    situationPrivateDesc: "Porodica, prijatelji",
    situationBuying: "Kupoprodaja",
    situationBuyingDesc: "Oglasi, dogovori",
    situationLove: "Muvanje 💕",
    situationLoveDesc: "IG, Messenger, uživo",
    situationBadNews: "Loše vijesti",
    situationBadNewsDesc: "Teške teme, ozbiljno",
    goalRemind: "Podsjetiti",
    goalRemindDesc: "Nekoga na nešto",
    goalRefuse: "Odbiti",
    goalRefuseDesc: "Zahtjev ili ponudu",
    goalAsk: "Zamoliti",
    goalAskDesc: "Za uslugu ili pomoć",
    goalCalm: "Smiriti",
    goalCalmDesc: "Napetu situaciju",
    goalClarify: "Razjasniti",
    goalClarifyDesc: "Nesporazum",
    goalOpener: "Započeti razgovor",
    goalOpenerDesc: "Ice-breaker, prva poruka",
    goalFlirt: "Flertovati",
    goalFlirtDesc: "Pokazati interes",
    goalCompliment: "Kompliment",
    goalComplimentDesc: "Originalan, kreativan",
    goalAskOut: "Pozvati na piće",
    goalAskOutDesc: "Kafu, izlazak, dejt",
    goalBreakup: "Raskid",
    goalBreakupDesc: "Prekinuti vezu",
    goalReject: "Odbiti nekoga",
    goalRejectDesc: "Bez povrijeđivanja",
    goalInform: "Saopštiti vijest",
    goalInformDesc: "Lošu informaciju",
    goalApologize: "Izviniti se",
    goalApologizeDesc: "Iskreno, od srca",
    tonePolite: "Ljubazno",
    tonePoliteDesc: "Prijateljski, toplo",
    toneProfessional: "Profesionalno",
    toneProfessionalDesc: "Jasno, samopouzdano",
    toneDirect: "Direktno",
    toneDirectDesc: "Iskreno, bez okolišanja",
    toneCalm: "Smireno",
    toneCalmDesc: "Kontrolisano, s razumijevanjem",
    tonePlayful: "Zaigrano",
    tonePlayfulDesc: "Šarmantno, duhovito",
    toneFlirty: "Flertovački",
    toneFlirtyDesc: "S podtekstom",
    toneGentle: "Nježno",
    toneGentleDesc: "Obzirno, empatično",
    createAccount: "Kreiraj račun",
    enterCredentials: "Unesite vaše podatke za prijavu",
    freeMessages: "Besplatno dobijate 5 poruka",
    wrongCredentials: "Pogrešan email ili lozinka",
    userExists: "Korisnik sa ovim emailom već postoji",
    confirmEmail: "Potvrdite email adresu",
    accountCreated: "Račun je kreiran. Možete se prijaviti.",
    noAccount: "Nemate račun? Registrujte se",
    hasAccount: "Već imate račun? Prijavite se",
    pleaseWait: "Molimo sačekajte...",
    premium: "Premium",
    messagesLeft: "poruka",
    usedMessages: "Iskorišteno",
    unlimited: "Neograničene poruke",
    freeLimit: "Besplatno: 5 poruka",
    signInToStart: "Prijavite se da počnete",
    subscribeForUnlimited: "Pretplata za neograničeno",
    limitReached: "Iskoristili ste svih 5 besplatnih poruka.",
    subscribe: "Pretplatite se za neograničeno",
    messageHistory: "Historija poruka",
    noHistory: "Još nemate generisanih poruka",
    error: "Greška",
    mustBeSignedIn: "Morate biti prijavljeni za generisanje poruka",
    invalidSession: "Nevalidna sesija. Prijavite se ponovo.",
    errorCheckingLimit: "Greška pri provjeri limita",
    errorGenerating: "Nije moguće generisati poruku. Pokušajte ponovo.",
    tooManyRequests: "Previše zahtjeva. Sačekajte malo i pokušajte ponovo.",
    serviceUnavailable: "Servis trenutno nije dostupan.",
    noResponse: "Nema odgovora od AI servisa",
  },
  me: {
    appName: "Poruke.AI",
    tagline: "Piši bolje, brže, lakše",
    signIn: "Prijavi se",
    signOut: "Odjavi se",
    signUp: "Registruj se",
    email: "Email",
    password: "Lozinka",
    back: "Nazad",
    next: "Dalje",
    generateMessage: "Generiši poruku",
    signInToGenerate: "Prijavi se za generisanje",
    newMessage: "Nova poruka",
    yourMessage: "Tvoja poruka",
    copyToClipboard: "Kopiraj",
    copied: "Kopirano!",
    regenerate: "Generiši ponovo",
    generating: "Generiše se poruka...",
    loading: "Učitavanje...",
    stepSituation: "Situacija",
    stepGoal: "Cilj",
    stepTone: "Ton",
    stepContext: "Kontekst",
    whatIsItAbout: "O čemu se radi?",
    whatDoYouWantToAchieve: "Šta želiš da postigneš?",
    howShouldItSound: "Kako da zvuči?",
    describeSituation: "Opiši situaciju",
    describeContext: "Ukratko objasni kontekst u 1-2 rečenice.",
    contextPlaceholder: "Npr: Kolega mi nije vratio pare već mjesec dana, a ne znam kako da ga podsjetim a da ne bude neprijatno...",
    situationWork: "Posao",
    situationWorkDesc: "Kolege, šefovi, klijenti",
    situationHousing: "Stanovanje",
    situationHousingDesc: "Stanodavci, komšije",
    situationPrivate: "Privatno",
    situationPrivateDesc: "Porodica, prijatelji",
    situationBuying: "Kupoprodaja",
    situationBuyingDesc: "Oglasi, dogovori",
    situationLove: "Muvanje 💕",
    situationLoveDesc: "IG, Messenger, uživo",
    situationBadNews: "Loše vijesti",
    situationBadNewsDesc: "Teške teme, ozbiljno",
    goalRemind: "Podsjetiti",
    goalRemindDesc: "Nekoga na nešto",
    goalRefuse: "Odbiti",
    goalRefuseDesc: "Zahtjev ili ponudu",
    goalAsk: "Zamoliti",
    goalAskDesc: "Za uslugu ili pomoć",
    goalCalm: "Smiriti",
    goalCalmDesc: "Napetu situaciju",
    goalClarify: "Razjasniti",
    goalClarifyDesc: "Nesporazum",
    goalOpener: "Započeti razgovor",
    goalOpenerDesc: "Ice-breaker, prva poruka",
    goalFlirt: "Flertovati",
    goalFlirtDesc: "Pokazati interes",
    goalCompliment: "Kompliment",
    goalComplimentDesc: "Originalan, kreativan",
    goalAskOut: "Pozvati na piće",
    goalAskOutDesc: "Kafu, izlazak, dejt",
    goalBreakup: "Raskid",
    goalBreakupDesc: "Prekinuti vezu",
    goalReject: "Odbiti nekoga",
    goalRejectDesc: "Bez povrijeđivanja",
    goalInform: "Saopštiti vijest",
    goalInformDesc: "Lošu informaciju",
    goalApologize: "Izviniti se",
    goalApologizeDesc: "Iskreno, od srca",
    tonePolite: "Ljubazno",
    tonePoliteDesc: "Prijateljski, toplo",
    toneProfessional: "Profesionalno",
    toneProfessionalDesc: "Jasno, samopouzdano",
    toneDirect: "Direktno",
    toneDirectDesc: "Iskreno, bez okolišanja",
    toneCalm: "Smireno",
    toneCalmDesc: "Kontrolisano, s razumijevanjem",
    tonePlayful: "Zaigrano",
    tonePlayfulDesc: "Šarmantno, duhovito",
    toneFlirty: "Flertovački",
    toneFlirtyDesc: "S podtekstom",
    toneGentle: "Nježno",
    toneGentleDesc: "Obzirno, empatično",
    createAccount: "Napravi nalog",
    enterCredentials: "Unesite vaše podatke za prijavu",
    freeMessages: "Besplatno dobijate 5 poruka",
    wrongCredentials: "Pogrešan email ili lozinka",
    userExists: "Korisnik sa ovim emailom već postoji",
    confirmEmail: "Potvrdite email adresu",
    accountCreated: "Nalog je napravljen. Možete se prijaviti.",
    noAccount: "Nemaš nalog? Registruj se",
    hasAccount: "Već imaš nalog? Prijavi se",
    pleaseWait: "Molimo sačekajte...",
    premium: "Premium",
    messagesLeft: "poruka",
    usedMessages: "Iskorišćeno",
    unlimited: "Neograničene poruke",
    freeLimit: "Besplatno: 5 poruka",
    signInToStart: "Prijavite se da počnete",
    subscribeForUnlimited: "Pretplata za neograničeno",
    limitReached: "Iskoristili ste svih 5 besplatnih poruka.",
    subscribe: "Pretplatite se za neograničeno",
    messageHistory: "Istorija poruka",
    noHistory: "Još nemaš generisanih poruka",
    error: "Greška",
    mustBeSignedIn: "Morate biti prijavljeni za generisanje poruka",
    invalidSession: "Nevalidna sesija. Prijavite se ponovo.",
    errorCheckingLimit: "Greška pri provjeri limita",
    errorGenerating: "Nije moguće generisati poruku. Pokušajte ponovo.",
    tooManyRequests: "Previše zahtjeva. Sačekajte malo i pokušajte ponovo.",
    serviceUnavailable: "Servis trenutno nije dostupan.",
    noResponse: "Nema odgovora od AI servisa",
  },
  mk: {
    appName: "Poruke.AI",
    tagline: "Пишувај подобро, побрзо, полесно",
    signIn: "Најави се",
    signOut: "Одјави се",
    signUp: "Регистрирај се",
    email: "Email",
    password: "Лозинка",
    back: "Назад",
    next: "Понатаму",
    generateMessage: "Генерирај порака",
    signInToGenerate: "Најави се за генерирање",
    newMessage: "Нова порака",
    yourMessage: "Твојата порака",
    copyToClipboard: "Копирај",
    copied: "Копирано!",
    regenerate: "Генерирај повторно",
    generating: "Се генерира порака...",
    loading: "Се вчитува...",
    stepSituation: "Ситуација",
    stepGoal: "Цел",
    stepTone: "Тон",
    stepContext: "Контекст",
    whatIsItAbout: "За што се работи?",
    whatDoYouWantToAchieve: "Што сакаш да постигнеш?",
    howShouldItSound: "Како треба да звучи?",
    describeSituation: "Опиши ја ситуацијата",
    describeContext: "Кратко објасни го контекстот во 1-2 реченици.",
    contextPlaceholder: "Пр: Колегата не ми ги врати парите веќе месец дена, а не знам како да го потсетам без да биде непријатно...",
    situationWork: "Работа",
    situationWorkDesc: "Колеги, шефови, клиенти",
    situationHousing: "Домување",
    situationHousingDesc: "Станодавци, соседи",
    situationPrivate: "Приватно",
    situationPrivateDesc: "Семејство, пријатели",
    situationBuying: "Купопродажба",
    situationBuyingDesc: "Огласи, договори",
    situationLove: "Мување 💕",
    situationLoveDesc: "IG, Messenger, во живо",
    situationBadNews: "Лоши вести",
    situationBadNewsDesc: "Тешки теми, сериозно",
    goalRemind: "Потсети",
    goalRemindDesc: "Некого на нешто",
    goalRefuse: "Одбиј",
    goalRefuseDesc: "Барање или понуда",
    goalAsk: "Замоли",
    goalAskDesc: "За услуга или помош",
    goalCalm: "Смири",
    goalCalmDesc: "Напната ситуација",
    goalClarify: "Разјасни",
    goalClarifyDesc: "Недоразбирање",
    goalOpener: "Започни разговор",
    goalOpenerDesc: "Ice-breaker, прва порака",
    goalFlirt: "Флертувај",
    goalFlirtDesc: "Покажи интерес",
    goalCompliment: "Комплимент",
    goalComplimentDesc: "Оригинален, креативен",
    goalAskOut: "Покани на пиење",
    goalAskOutDesc: "Кафе, излегување, дејт",
    goalBreakup: "Раскинување",
    goalBreakupDesc: "Прекини врска",
    goalReject: "Одбиј некого",
    goalRejectDesc: "Без повредување",
    goalInform: "Соопшти вест",
    goalInformDesc: "Лоша информација",
    goalApologize: "Извини се",
    goalApologizeDesc: "Искрено, од срце",
    tonePolite: "Љубезно",
    tonePoliteDesc: "Пријателски, топло",
    toneProfessional: "Професионално",
    toneProfessionalDesc: "Јасно, самоуверено",
    toneDirect: "Директно",
    toneDirectDesc: "Искрено, без заобиколување",
    toneCalm: "Смирено",
    toneCalmDesc: "Контролирано, со разбирање",
    tonePlayful: "Разиграно",
    tonePlayfulDesc: "Шармантно, духовито",
    toneFlirty: "Флертовачки",
    toneFlirtyDesc: "Со подтекст",
    toneGentle: "Нежно",
    toneGentleDesc: "Обѕирно, емпатично",
    createAccount: "Креирај сметка",
    enterCredentials: "Внесете ги вашите податоци за најава",
    freeMessages: "Бесплатно добивате 5 пораки",
    wrongCredentials: "Погрешен email или лозинка",
    userExists: "Корисник со овој email веќе постои",
    confirmEmail: "Потврдете ја email адресата",
    accountCreated: "Сметката е креирана. Можете да се најавите.",
    noAccount: "Немате сметка? Регистрирајте се",
    hasAccount: "Веќе имате сметка? Најавете се",
    pleaseWait: "Ве молиме почекајте...",
    premium: "Premium",
    messagesLeft: "пораки",
    usedMessages: "Искористено",
    unlimited: "Неограничени пораки",
    freeLimit: "Бесплатно: 5 пораки",
    signInToStart: "Најавете се за да почнете",
    subscribeForUnlimited: "Претплата за неограничено",
    limitReached: "Ги искористивте сите 5 бесплатни пораки.",
    subscribe: "Претплатете се за неограничено",
    messageHistory: "Историја на пораки",
    noHistory: "Сè уште немате генерирани пораки",
    error: "Грешка",
    mustBeSignedIn: "Мора да сте најавени за генерирање пораки",
    invalidSession: "Невалидна сесија. Најавете се повторно.",
    errorCheckingLimit: "Грешка при проверка на лимит",
    errorGenerating: "Не е можно да се генерира порака. Обидете се повторно.",
    tooManyRequests: "Премногу барања. Почекајте малку и обидете се повторно.",
    serviceUnavailable: "Сервисот моментално не е достапен.",
    noResponse: "Нема одговор од AI сервисот",
  },
  sl: {
    appName: "Poruke.AI",
    tagline: "Piši bolje, hitreje, lažje",
    signIn: "Prijava",
    signOut: "Odjava",
    signUp: "Registracija",
    email: "Email",
    password: "Geslo",
    back: "Nazaj",
    next: "Naprej",
    generateMessage: "Generiraj sporočilo",
    signInToGenerate: "Prijavi se za generiranje",
    newMessage: "Novo sporočilo",
    yourMessage: "Tvoje sporočilo",
    copyToClipboard: "Kopiraj",
    copied: "Kopirano!",
    regenerate: "Generiraj ponovno",
    generating: "Generiranje sporočila...",
    loading: "Nalaganje...",
    stepSituation: "Situacija",
    stepGoal: "Cilj",
    stepTone: "Ton",
    stepContext: "Kontekst",
    whatIsItAbout: "Za kaj gre?",
    whatDoYouWantToAchieve: "Kaj želiš doseči?",
    howShouldItSound: "Kako naj zveni?",
    describeSituation: "Opiši situacijo",
    describeContext: "Na kratko pojasni kontekst v 1-2 stavkih.",
    contextPlaceholder: "Npr: Kolega mi že mesec dni ni vrnil denarja, ne vem pa, kako ga opomniti, da ne bo neprijetno...",
    situationWork: "Delo",
    situationWorkDesc: "Kolegi, šefi, stranke",
    situationHousing: "Stanovanje",
    situationHousingDesc: "Najemodajalci, sosedje",
    situationPrivate: "Zasebno",
    situationPrivateDesc: "Družina, prijatelji",
    situationBuying: "Nakup/prodaja",
    situationBuyingDesc: "Oglasi, dogovori",
    situationLove: "Zapeljevanje 💕",
    situationLoveDesc: "IG, Messenger, v živo",
    situationBadNews: "Slabe novice",
    situationBadNewsDesc: "Težke teme, resno",
    goalRemind: "Opomniti",
    goalRemindDesc: "Nekoga na nekaj",
    goalRefuse: "Zavrniti",
    goalRefuseDesc: "Prošnjo ali ponudbo",
    goalAsk: "Prositi",
    goalAskDesc: "Za uslugo ali pomoč",
    goalCalm: "Pomiriti",
    goalCalmDesc: "Napeto situacijo",
    goalClarify: "Razjasniti",
    goalClarifyDesc: "Nesporazum",
    goalOpener: "Začeti pogovor",
    goalOpenerDesc: "Ice-breaker, prvo sporočilo",
    goalFlirt: "Flirtati",
    goalFlirtDesc: "Pokazati zanimanje",
    goalCompliment: "Kompliment",
    goalComplimentDesc: "Originalen, kreativen",
    goalAskOut: "Povabiti na pijačo",
    goalAskOutDesc: "Kavo, zmenek, dejt",
    goalBreakup: "Prekinitev",
    goalBreakupDesc: "Prekiniti razmerje",
    goalReject: "Zavrniti nekoga",
    goalRejectDesc: "Brez prizadetja",
    goalInform: "Sporočiti novico",
    goalInformDesc: "Slabo informacijo",
    goalApologize: "Opravičiti se",
    goalApologizeDesc: "Iskreno, od srca",
    tonePolite: "Vljudno",
    tonePoliteDesc: "Prijazno, toplo",
    toneProfessional: "Profesionalno",
    toneProfessionalDesc: "Jasno, samozavestno",
    toneDirect: "Neposredno",
    toneDirectDesc: "Iskreno, brez ovijanja",
    toneCalm: "Umirjeno",
    toneCalmDesc: "Kontrolirano, z razumevanjem",
    tonePlayful: "Igrivo",
    tonePlayfulDesc: "Šarmantno, duhovito",
    toneFlirty: "Flirtovsko",
    toneFlirtyDesc: "Z namigom",
    toneGentle: "Nežno",
    toneGentleDesc: "Obzirno, empatično",
    createAccount: "Ustvari račun",
    enterCredentials: "Vnesite svoje podatke za prijavo",
    freeMessages: "Brezplačno dobite 5 sporočil",
    wrongCredentials: "Napačen email ali geslo",
    userExists: "Uporabnik s tem emailom že obstaja",
    confirmEmail: "Potrdite email naslov",
    accountCreated: "Račun je ustvarjen. Lahko se prijavite.",
    noAccount: "Nimate računa? Registrirajte se",
    hasAccount: "Že imate račun? Prijavite se",
    pleaseWait: "Prosim počakajte...",
    premium: "Premium",
    messagesLeft: "sporočil",
    usedMessages: "Porabljeno",
    unlimited: "Neomejeno sporočil",
    freeLimit: "Brezplačno: 5 sporočil",
    signInToStart: "Prijavite se za začetek",
    subscribeForUnlimited: "Naročnina za neomejeno",
    limitReached: "Porabili ste vseh 5 brezplačnih sporočil.",
    subscribe: "Naročite se za neomejeno",
    messageHistory: "Zgodovina sporočil",
    noHistory: "Še nimate generiranih sporočil",
    error: "Napaka",
    mustBeSignedIn: "Za generiranje sporočil morate biti prijavljeni",
    invalidSession: "Neveljavna seja. Prijavite se ponovno.",
    errorCheckingLimit: "Napaka pri preverjanju limita",
    errorGenerating: "Sporočila ni mogoče generirati. Poskusite znova.",
    tooManyRequests: "Preveč zahtev. Počakajte malo in poskusite znova.",
    serviceUnavailable: "Storitev trenutno ni na voljo.",
    noResponse: "Ni odgovora od AI storitve",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  languageInfo: LanguageInfo;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const STORAGE_KEY = "poruke-language";

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem(STORAGE_KEY);
    return (saved as Language) || "sr";
  });

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.sr[key] || key;
  };

  const languageInfo = languages.find(l => l.code === language) || languages[0];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languageInfo }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
